networks:
  monitoring:
    driver: bridge

services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    image: xchangepass-app
    container_name: spring-app
    volumes:
      - ./logs:/logs
    restart: always
    depends_on:
      - postgres
      - redis
      - mongodb
      - influxdb
      - prometheus
      - loki
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/xchangepass
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/xchangepass
      - DB_HOST=influxdb
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    restart: always
    volumes:
      - ./logs:/logs  # 로그 디렉토리 (Spring 로그 저장 위치)
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./positions.yaml:/tmp/positions.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - monitoring


  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki-data/wal:/loki/wal
      - ./loki-data/compactor:/loki/compactor
      - ./loki/data:/loki
    networks:
      - monitoring

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - monitoring
    command: [
      "redis-server",
      "--save", "900 1",            # 900초(15분)마다 최소 1개 이상의 변경이 있으면 스냅샷 저장
      "--save", "300 10",           # 300초(5분)마다 최소 10개 이상의 변경이 있으면 저장
      "--save", "60 1000",          # 60초마다 최소 1000개의 변경사항이 있으면 저장
      "--appendonly", "yes",        # AOF 활성화
      "--appendfsync", "everysec", # 1초마다 디스크에 기록
      "--auto-aof-rewrite-percentage", "100",  # AOF 크기가 100% 커지면 리라이트
      "--auto-aof-rewrite-min-size", "64mb"   # AOF 크기가 최소 64MB일 때 리라이트
    ]

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xchangepass
    volumes:
      - postgres_data:/var/lib/postgresql/data  # DB 데이터 유지
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - monitoring
    volumes:
      - mongo_data:/data/db

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks:
      - monitoring
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  k6:
    image: grafana/k6:latest
    container_name: k6
    networks:
      - monitoring
    depends_on:
      - influxdb
      - app
    volumes:
      - ./k6-scripts:/k6-scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6

  # 🔹 Spring Boot 애플리케이션


volumes:
  redis-data:
  postgres_data:
  mongo_data:
  grafana-storage:
