name: Bug Report
description: 버그를 보고하고 해결하기 위한 템플릿입니다.
title: "[Fix] "
labels: ["🐞 BugFix"]

body:
  - type: input
    id: parentKey
    attributes:
      label: "📌 상위 작업 Ticket Number"
      description: "이 버그가 특정 작업과 관련이 있다면, 해당 JIRA 티켓 번호를 입력해주세요. (선택 사항)"
      placeholder: "KAN-00"
    validations:
      required: false

  - type: input
    id: bug_summary
    attributes:
      label: "🔍 버그 요약"
      description: "버그의 핵심 내용을 간단히 작성해주세요."
      placeholder: "예: 페이지가 로드되지 않음"
    validations:
      required: true

  - type: textarea
    id: bug_occurrence
    attributes:
      label: "🕒 버그 발생 상황"
      description: "어떤 환경에서, 어떤 상황에서 버그가 발생했는지 Given-When-Then 형식으로 작성해주세요."
      placeholder: |
        예:
        - Given: 사용자가 로그인한 상태에서
        - When: 프로필 업데이트 버튼을 클릭하면
        - Then: '500 Internal Server Error'가 발생함
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: "🎯 예상 결과"
      description: "버그가 없었다면 어떻게 동작해야 하는지 설명해주세요."
      placeholder: "예: 페이지가 정상적으로 로드되어야 함"
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: "🚨 실제 결과"
      description: "현재 발생하는 문제의 실제 동작을 설명해주세요."
      placeholder: "예: '페이지를 불러오는 중 오류가 발생했습니다' 라는 메시지가 나타남"
    validations:
      required: true

  - type: input
    id: startdate
    attributes:
      label: "🗓️ 버그 수정 시작일"
      description: "이슈 해결을 시작할 날짜를 입력해주세요."
      placeholder: "yyyy-mm-dd"
    validations:
      required: true

  - type: input
    id: enddate
    attributes:
      label: "🗓️ 버그 수정 완료 목표일"
      description: "이슈 해결 목표 날짜를 입력해주세요."
      placeholder: "yyyy-mm-dd"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🔄 재현 방법"
      description: "버그를 재현하기 위한 단계별 설명을 적어주세요."
      placeholder: |
        1. 홈페이지에 접속한다.
        2. 로그인 버튼을 클릭한다.
        3. 페이지가 새로고침되며 '500 Internal Server Error'가 발생한다.
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: "📚 참고 자료 (선택)"
      description: "관련된 스크린샷, 로그, 링크 등을 첨부해주세요."
      placeholder: "예: 오류 로그, 실행 환경 정보, 관련 문서 등"
