#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

RUN_TRANSACTION_STATISTICS_PG_STAT_STATEMENTS=true \
TRANSACTION_STATISTICS_BENCHMARK_ROWS="${TRANSACTION_STATISTICS_BENCHMARK_ROWS:-100000}" \
TRANSACTION_STATISTICS_BENCHMARK_USERS="${TRANSACTION_STATISTICS_BENCHMARK_USERS:-1000}" \
TRANSACTION_STATISTICS_BENCHMARK_MONTHS="${TRANSACTION_STATISTICS_BENCHMARK_MONTHS:-12}" \
TRANSACTION_STATISTICS_BENCHMARK_SEED="${TRANSACTION_STATISTICS_BENCHMARK_SEED:-20260704}" \
TRANSACTION_STATISTICS_PGSTAT_ITERATIONS="${TRANSACTION_STATISTICS_PGSTAT_ITERATIONS:-20}" \
./gradlew test --tests '*TransactionStatisticsPgStatStatementsTest'

echo "pg_stat_statements CSV: $ROOT_DIR/build/perf/pg-stat-statements/transaction-statistics-pg-stat-statements.csv"
