#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

RUN_TRANSACTION_STATISTICS_EXPLAIN=true \
TRANSACTION_STATISTICS_BENCHMARK_ROWS="${TRANSACTION_STATISTICS_BENCHMARK_ROWS:-100000}" \
TRANSACTION_STATISTICS_BENCHMARK_USERS="${TRANSACTION_STATISTICS_BENCHMARK_USERS:-1000}" \
TRANSACTION_STATISTICS_BENCHMARK_MONTHS="${TRANSACTION_STATISTICS_BENCHMARK_MONTHS:-12}" \
TRANSACTION_STATISTICS_BENCHMARK_SEED="${TRANSACTION_STATISTICS_BENCHMARK_SEED:-20260704}" \
./gradlew test --tests '*TransactionStatisticsExplainAnalyzeTest'

echo "EXPLAIN ANALYZE plans: $ROOT_DIR/build/perf/explain"
