#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

RUN_TRANSACTION_STATISTICS_TABLE_STATS=true \
TRANSACTION_STATISTICS_BENCHMARK_ROWS="${TRANSACTION_STATISTICS_BENCHMARK_ROWS:-100000}" \
TRANSACTION_STATISTICS_BENCHMARK_USERS="${TRANSACTION_STATISTICS_BENCHMARK_USERS:-1000}" \
TRANSACTION_STATISTICS_BENCHMARK_MONTHS="${TRANSACTION_STATISTICS_BENCHMARK_MONTHS:-12}" \
TRANSACTION_STATISTICS_BENCHMARK_SEED="${TRANSACTION_STATISTICS_BENCHMARK_SEED:-20260704}" \
TRANSACTION_STATISTICS_TABLE_STATS_REFRESH_REPEAT="${TRANSACTION_STATISTICS_TABLE_STATS_REFRESH_REPEAT:-5}" \
./gradlew test --tests '*TransactionStatisticsTableStatsTest'

echo "Table stats CSV: $ROOT_DIR/build/perf/table-stats/transaction-statistics-table-stats.csv"
