CREATE TABLE IF NOT EXISTS wallet_balance_reconciliation_issue (
    issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    snapshot_amount NUMERIC(19, 4) NOT NULL,
    ledger_calculated_amount NUMERIC(19, 4) NOT NULL,
    difference_amount NUMERIC(19, 4) NOT NULL,
    basis_time TIMESTAMP(6) NOT NULL,
    status VARCHAR(20) NOT NULL,
    first_detected_at TIMESTAMP(6) NOT NULL,
    last_detected_at TIMESTAMP(6) NOT NULL,
    detection_count BIGINT NOT NULL,
    version BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_wallet_balance_reconciliation_issue_open
ON wallet_balance_reconciliation_issue(wallet_id, currency)
WHERE status = 'OPEN';
